apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oo7s7r12r-java-quarkus
  janus-idp.io/tekton: oo7s7r12r-java-quarkus
  backstage.io/kubernetes-id: oo7s7r12r-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oo7s7r12r-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
